auto: true

markdown: kramdown
#pygments: true
highlighter: rouge
paginate: 8
permalink: /:title/

title: SamirChen
url: http://www.samirchen.com
feed: /atom.xml
author_info: <a href="http://www.samirchen.com/">SamirChen</a>
