auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: SamirChen
url: http://samirchen-non.com
feed: /atom.xml
author_info: <a href="http://samirchen-non.com/">SamirChen</a>
